### ISSUE TITLE
Building on arch yields:

### ISSUE THREAD

**Issue by ergpopler** [antoyo/titanium#27] opened 2020-10-30 22:35 UTC
parrot@arch: ~/Makes/titanium $ titanium

** (titanium:184406): WARNING **: 18:33:14.611: webkit_web_context_set_web_process_count_limit is deprecated and does nothing. Limiting the number of web processes is no longer possible for security reasons

** (titanium:184406): WARNING **: 18:33:14.611: webkit_web_context_set_web_process_count_limit is deprecated and does nothing. Limiting the number of web processes is no longer possible for security reasons
Cannot initialize the logger: A terminal could not be opened
thread '<unnamed>' panicked at 'attempted to leave type `std::mem::ManuallyDrop<std::vec::Vec<u64>>` uninitialized, which is invalid', /rustc/ffa2e7ae8fbf9badc035740db949b9dae271c29f/library/core/src/mem/mod.rs:659:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
^C

and on the bottom of the screen it says `The web process crashed.`

Compiled just fine, following the instructions in the readme, but at runtime it gives the above error.

Building on Pop!_OS/Ubuntu works just fine.

**Comment by antoyo** [comment] 2020-10-30 22:58
Can you run it with `RUST_BACKTRACE=1` to show me a better stack-trace, as I cannot reproduce this issue on ArchLinux?

When you say it `works just fine` on Ubuntu, do you mean you can run it without any issue?

**Comment by ergpopler** [comment] 2020-10-30 23:48
well it runs just fine and works as a browser, but the thing #26  doesn't work

**Comment by nfisher1226** [comment] 2021-01-11 16:41
RUST_BACKTRACE=1 titanium

** (titanium:38182): WARNING **: 11:38:22.338: webkit_web_context_set_web_process_count_limit is deprecated and does nothing. Limiting the number of web processes is no longer possible for security reasons

** (titanium:38182): WARNING **: 11:38:22.339: webkit_web_context_set_web_process_count_limit is deprecated and does nothing. Limiting the number of web processes is no longer possible for security reasons

Cannot initialize the logger: A terminal could not be opened
thread '<unnamed>' panicked at 'attempted to leave type `std::mem::ManuallyDrop<std::vec::Vec<u64>>` uninitialized, which is invalid', /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/mem/mod.rs:671:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c97f11af7bc4a6d3578f6a953be04ab2449a5728/library/core/src/panicking.rs:50:5
   3: adblock::blocker::Blocker::check_parameterised
   4: adblock::engine::Engine::check_network_urls
   5: std::thread::local::LocalKey<T>::with
   6: titanium_web_extension::message_client::block_request
   7: <O as webkit2gtk_webextension::auto::web_page::WebPageExt>::connect_send_request::send_request_trampoline
   8: <unknown>
   9: <unknown>
  10: g_cclosure_marshal_generic
  11: g_closure_invoke
  12: <unknown>
  13: g_signal_emit_valist
  14: g_signal_emit
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: _ZN3WTF7RunLoop11performWorkEv
  42: <unknown>
  43: <unknown>
  44: g_main_context_dispatch
  45: <unknown>
  46: g_main_loop_run
  47: _ZN3WTF7RunLoop3runEv
  48: _ZN6WebKit14WebProcessMainEiPPc
  49: __libc_start_main
  50: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5

**Comment by antoyo** [comment] 2021-01-30 20:21
This was due to [this issue](https://github.com/brave/adblock-rust/issues/147) and is fixed by 691f677.

**Closed as completed** 2021-01-30 20:20 UTC
